// ============================================================
// FOODS CARNIVAL - Complete Restaurant Data
// Extracted from official CDR Menu Design
// Contact: foodscarnival.wah@gmail.com
// Phone: 0316-4640160 | WhatsApp: 0316-4640160
// Location: Shop No 7/8 Market Masjid Ahle Hadees Laiq Ali Chowk Wah Cantt
// ============================================================

const RESTAURANT_INFO = {
  name: "Foods Carnival",
  tagline: "Fast Food & Refreshment Point",
  phone: "0316-4640160",
  whatsapp: "03164640160",
  email: "foodscarnival.wah@gmail.com",
  location: "Shop No 7/8 Market Masjid Ahle Hadees Laiq Ali Chowk Wah Cantt.",
  deliveryRadius: "3 KM",
  deliveryFee: 0,
  currency: "Rs.",
  primaryColor: "#B8001F",
  accentColor: "#FFD700",
};

const MENU_CATEGORIES = [
  {
    id: "regular-pizza",
    name: "Regular Pizza",
    icon: "🍕",
    emoji: "🍕",
    items: [
      {
        id: "rp1",
        name: "BBQ Pizza",
        sizes: [
          { label: "Small", price: 200 },
          { label: "Medium", price: 400 },
          { label: "Large", price: 699 },
        ],
        basePrice: 200,
        description: "Classic BBQ pizza with rich smoky flavors",
        badge: null,
      },
      {
        id: "rp2",
        name: "Arabic Wrap",
        sizes: [
          { label: "Small", price: 200 },
          { label: "Medium", price: 400 },
          { label: "Large", price: 699 },
        ],
        basePrice: 200,
        description: "Arabic style pizza wrap",
        badge: null,
      },
      {
        id: "rp3",
        name: "Fajita Pizza",
        sizes: [
          { label: "Small", price: 200 },
          { label: "Medium", price: 400 },
          { label: "Large", price: 699 },
        ],
        basePrice: 200,
        description: "Sizzling fajita toppings on crispy crust",
        badge: null,
      },
    ],
  },
  {
    id: "special-pizza",
    name: "Special Pizza",
    icon: "⭐",
    emoji: "⭐",
    items: [
      {
        id: "sp1",
        name: "Foods Carnival Pizza",
        sizes: [
          { label: "Small", price: 449 },
          { label: "Medium", price: 799 },
          { label: "Large", price: 1199 },
        ],
        basePrice: 449,
        description: "Our signature pizza — loaded with premium toppings",
        badge: "Signature",
      },
      {
        id: "sp2",
        name: "Zinger Pizza",
        sizes: [
          { label: "Small", price: 449 },
          { label: "Medium", price: 799 },
          { label: "Large", price: 1199 },
        ],
        basePrice: 449,
        description: "Spicy zinger chicken on pizza",
        badge: null,
      },
      {
        id: "sp3",
        name: "Crown Crust Pizza",
        sizes: [
          { label: "Small", price: 449 },
          { label: "Medium", price: 799 },
          { label: "Large", price: 1199 },
        ],
        basePrice: 449,
        description: "Crown crust with stuffed edges",
        badge: "Special",
      },
      {
        id: "sp4",
        name: "Pepperoni Pizza",
        sizes: [
          { label: "Small", price: 449 },
          { label: "Medium", price: 799 },
          { label: "Large", price: 1199 },
        ],
        basePrice: 449,
        description: "Classic pepperoni with mozzarella",
        badge: null,
      },
      {
        id: "sp5",
        name: "Love Zinger Burger",
        sizes: [
          { label: "Small", price: 449 },
          { label: "Medium", price: 799 },
          { label: "Large", price: 1199 },
        ],
        basePrice: 449,
        description: "Special love zinger pizza burger",
        badge: null,
      },
      {
        id: "sp6",
        name: "Lasagne Pizza",
        sizes: [
          { label: "Small", price: 449 },
          { label: "Medium", price: 799 },
          { label: "Large", price: 1199 },
        ],
        basePrice: 449,
        description: "Lasagne style layered pizza",
        badge: null,
      },
      {
        id: "sp7",
        name: "Mafia Pizza",
        sizes: [
          { label: "Small", price: 449 },
          { label: "Medium", price: 799 },
          { label: "Large", price: 1199 },
        ],
        basePrice: 449,
        description: "Bold and loaded — the Mafia special",
        badge: "Hot",
      },
    ],
  },
  {
    id: "pasta",
    name: "Pasta",
    icon: "🍝",
    emoji: "🍝",
    items: [
      {
        id: "pa1",
        name: "Foods Carnival Pasta",
        price: 299,
        description: "Our signature pasta in special sauce",
        badge: "Signature",
      },
      {
        id: "pa2",
        name: "Chicken Pasta",
        price: 299,
        description: "Creamy chicken pasta",
        badge: null,
      },
      {
        id: "pa3",
        name: "Mashroomm Pasta",
        price: 299,
        description: "Mushroom pasta with creamy white sauce",
        badge: null,
      },
      {
        id: "pa4",
        name: "Alfredo Pasta",
        price: 299,
        description: "Classic Alfredo pasta",
        badge: null,
      },
    ],
  },
  {
    id: "buff-ball",
    name: "Buff Ball",
    icon: "🧆",
    emoji: "🧆",
    items: [
      {
        id: "bb1",
        name: "Buff Ball (2 Pieces)",
        price: 299,
        description: "2 pieces crispy buff balls",
        badge: null,
      },
      {
        id: "bb2",
        name: "Chickenate (3 Pieces)",
        price: 299,
        description: "3 pieces chicken bites",
        badge: null,
      },
    ],
  },
  {
    id: "wraps",
    name: "Wraps",
    icon: "🌯",
    emoji: "🌯",
    items: [
      {
        id: "wr1",
        name: "Afghan Wrap",
        price: 349,
        description: "Afghan style wrap with special spices",
        badge: null,
      },
      {
        id: "wr2",
        name: "Food Carnival Wrap",
        price: 349,
        description: "Our signature carnival wrap",
        badge: "Signature",
      },
      {
        id: "wr3",
        name: "Arabic Wrap",
        price: 349,
        description: "Authentic Arabic style wrap",
        badge: null,
      },
      {
        id: "wr4",
        name: "Zinger Crispy Wrap",
        price: 349,
        description: "Crispy zinger chicken in wrap",
        badge: "Crispy",
      },
    ],
  },
  {
    id: "burgers",
    name: "Burgers",
    icon: "🍔",
    emoji: "🍔",
    items: [
      {
        id: "bu1",
        name: "Zinger Cheese Burger",
        price: 299,
        description: "Crispy zinger with melted cheese",
        badge: null,
      },
      {
        id: "bu2",
        name: "Chicken Burger",
        price: 299,
        description: "Classic chicken burger",
        badge: null,
      },
      {
        id: "bu3",
        name: "Jalapeno Burger",
        price: 299,
        description: "Spicy jalapeno burger",
        badge: "Spicy 🌶️",
      },
      {
        id: "bu4",
        name: "Love Zinger Burger",
        price: 299,
        description: "Extra loaded love zinger",
        badge: null,
      },
      {
        id: "bu5",
        name: "Chicken Burger",
        price: 299,
        description: "Juicy chicken burger",
        badge: null,
      },
      {
        id: "bu6",
        name: "Chicken Egg Burger",
        price: 299,
        description: "Chicken burger topped with egg",
        badge: null,
      },
    ],
  },
  {
    id: "shawarma",
    name: "Shawarma",
    icon: "🥙",
    emoji: "🥙",
    items: [
      {
        id: "sh1",
        name: "Chicken Shawarma",
        price: 299,
        description: "Classic chicken shawarma roll",
        badge: null,
      },
      {
        id: "sh2",
        name: "Arabic Shawarma",
        price: 299,
        description: "Arabic style with garlic sauce",
        badge: null,
      },
      {
        id: "sh3",
        name: "Zinger Shawarma",
        price: 299,
        description: "Crispy zinger shawarma",
        badge: "Crispy",
      },
      {
        id: "sh4",
        name: "Chicken Shawarma",
        price: 299,
        description: "Tender chicken shawarma",
        badge: null,
      },
    ],
  },
  {
    id: "fried-wings",
    name: "Fried Wings",
    icon: "🍗",
    emoji: "🍗",
    items: [
      {
        id: "fw1",
        name: "Fried Wings",
        price: 249,
        description: "Crispy golden fried wings",
        badge: null,
      },
      {
        id: "fw2",
        name: "Over Fried Wings",
        price: 349,
        description: "Extra crispy over-fried wings",
        badge: null,
      },
      {
        id: "fw3",
        name: "Buffalo Wings",
        price: 249,
        description: "Tangy buffalo sauce wings",
        badge: "Hot 🔥",
      },
    ],
  },
  {
    id: "fries",
    name: "Fries",
    icon: "🍟",
    emoji: "🍟",
    items: [
      {
        id: "fr1",
        name: "Normal Fries",
        price: 149,
        description: "Classic golden fries",
        badge: null,
      },
      {
        id: "fr2",
        name: "Masala Fries",
        price: 199,
        description: "Spiced masala seasoned fries",
        badge: "Popular",
      },
      {
        id: "fr3",
        name: "Loaded Fries",
        price: 249,
        description: "Loaded with toppings and sauce",
        badge: "Loaded",
      },
      {
        id: "fr4",
        name: "Malka Fries",
        price: 299,
        description: "Premium malka style fries",
        badge: null,
      },
    ],
  },
  {
    id: "sandwich",
    name: "Sandwich",
    icon: "🥪",
    emoji: "🥪",
    items: [
      {
        id: "sa1",
        name: "Chicken Sandwich",
        price: 299,
        description: "Classic chicken sandwich",
        badge: null,
      },
      {
        id: "sa2",
        name: "Zinger Sandwich",
        price: 299,
        description: "Crispy zinger sandwich",
        badge: null,
      },
    ],
  },
  {
    id: "paratha-roll",
    name: "Paratha Roll",
    icon: "🫓",
    emoji: "🫓",
    items: [
      {
        id: "pr1",
        name: "Chicken Paratha",
        price: 349,
        description: "Chicken filled paratha roll",
        badge: null,
      },
      {
        id: "pr2",
        name: "Zinger Paratha",
        price: 349,
        description: "Zinger chicken paratha roll",
        badge: null,
      },
      {
        id: "pr3",
        name: "Food Carnival Paratha",
        price: 349,
        description: "Our signature paratha roll",
        badge: "Signature",
      },
    ],
  },
  {
    id: "soda",
    name: "Soda Section",
    icon: "🥤",
    emoji: "🥤",
    items: [
      {
        id: "so1",
        name: "2 Liter Bottle",
        price: 150,
        description: "2 Liter chilled soda bottle",
        badge: null,
      },
      {
        id: "so2",
        name: "1 Liter Drink",
        price: 100,
        description: "1 Liter chilled drink",
        badge: null,
      },
      {
        id: "so3",
        name: "Fresh Lemon Soda",
        price: 100,
        description: "Fresh squeezed lemon soda",
        badge: "Fresh",
      },
      {
        id: "so4",
        name: "Mirinda Lemon Soda",
        price: 55,
        description: "Mirinda lemon flavored soda",
        badge: null,
      },
      {
        id: "so5",
        name: "Mint Margarita",
        price: 150,
        description: "Fresh mint margarita mocktail",
        badge: "Fresh",
      },
      {
        id: "so6",
        name: "With Milk Soda",
        price: 290,
        description: "Soda blended with milk",
        badge: null,
      },
    ],
  },
  {
    id: "refreshment",
    name: "Refreshment",
    icon: "🍑",
    emoji: "🍑",
    items: [
      {
        id: "re1",
        name: "Taday-Made Bell Samosa",
        price: 13,
        description: "Freshly made bell samosa per piece",
        badge: "Fresh",
      },
      {
        id: "re2",
        name: "Dahi Phulki",
        price: 320,
        description: "Traditional dahi phulki",
        badge: null,
      },
      {
        id: "re3",
        name: "Gol Gappay",
        price: 320,
        description: "Crispy gol gappay with tamarind water",
        badge: null,
      },
      {
        id: "re4",
        name: "Chaat",
        price: 320,
        description: "Spicy tangy chaat",
        badge: null,
      },
      {
        id: "re5",
        name: "Fruit Chaat",
        price: 320,
        description: "Fresh fruit chaat",
        badge: "Fresh",
      },
    ],
  },
];

const DEALS = [
  {
    id: "deal-1",
    name: "Deal No 1",
    price: 360,
    badge: "Best Value",
    color: "#8B0000",
    items: [
      "1 Zinger Burger",
      "1 Regular Fries",
      "1 Pepsi Cold Drink",
    ],
    description: "Perfect starter deal for one",
    popular: false,
  },
  {
    id: "deal-2",
    name: "Deal No 2",
    price: 350,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Fried Wing",
      "1 Regular Fries",
      "1 Pepsi Cold Drink",
    ],
    description: "Crispy wings deal",
    popular: false,
  },
  {
    id: "deal-3",
    name: "Deal No 3",
    price: 700,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Regular Pizza (Small)",
      "1 Pepsi Gold Drink",
    ],
    description: "Pizza & drink combo",
    popular: false,
  },
  {
    id: "deal-4",
    name: "Deal No 4",
    price: 600,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Zinger Burger",
      "1 Fried Wing",
      "1 Regular Fries",
      "1 Pepsi Cold Drink",
    ],
    description: "Full meal for one",
    popular: false,
  },
  {
    id: "deal-5",
    name: "Deal No 5",
    price: 560,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Small",
      "1 Regular Fries",
      "1 Pepsi Cold Drink",
    ],
    description: "Small deal value combo",
    popular: false,
  },
  {
    id: "deal-6",
    name: "Deal No 6",
    price: 1150,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Medium Pizza",
      "1 Regular Fries",
      "2 Chicken Biscuits",
      "1 Maaza Cold Drink",
    ],
    description: "Medium pizza meal deal",
    popular: false,
  },
  {
    id: "deal-7",
    name: "Deal No 7",
    price: 980,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Maaza",
      "1 Regular Fries",
      "1 Maaza Cold Drink",
    ],
    description: "Economy deal",
    popular: false,
  },
  {
    id: "deal-8",
    name: "Deal No 8",
    price: 1150,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Fried Wings",
      "1 Regular Fries",
      "1 Maaza Cold Drink",
    ],
    description: "Wings & fries deal",
    popular: false,
  },
  {
    id: "deal-9",
    name: "Deal No 9",
    price: 560,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Zinger Burger",
      "2 Zinger Burgers",
      "1 Regular Fries",
      "1 Pepsi Cold Drink",
    ],
    description: "Double burger deal",
    popular: false,
  },
  {
    id: "deal-10",
    name: "Deal No 10",
    price: 1999,
    badge: "🔥 Deal of the Day",
    color: "#B8001F",
    items: [
      "2 Zinger Burgers",
      "2 Fried Wings",
      "2 Regular Fries",
      "1 Reg Cold Drink",
    ],
    description: "Mega value family deal",
    popular: true,
  },
  {
    id: "deal-11",
    name: "Deal No 11",
    price: 950,
    badge: null,
    color: "#8B0000",
    items: [
      "Chicken Honey",
      "1 Reg Gold Drink",
    ],
    description: "Chicken honey special",
    popular: false,
  },
  {
    id: "deal-12",
    name: "Deal No 12",
    price: 430,
    badge: null,
    color: "#8B0000",
    items: [
      "1 Zinger Burger",
      "1 Regular Fries",
    ],
    description: "Simple burger combo",
    popular: false,
  },
  {
    id: "deal-13",
    name: "Dinner Deal",
    price: 1280,
    badge: "🌙 Dinner Special",
    color: "#4B0082",
    items: [
      "2 Zinger Burgers",
      "1 Regular Fries",
      "1 Pepsi Cold Drink",
    ],
    description: "Perfect dinner for two",
    popular: true,
  },
  {
    id: "deal-14",
    name: "Deal No 14",
    price: 650,
    badge: null,
    color: "#8B0000",
    items: [
      "10 Wings",
      "1 Regular Fries",
      "1 Pepsi Cold Drink",
    ],
    description: "Wings bucket deal",
    popular: false,
  },
  {
    id: "deal-15",
    name: "Family Deal",
    price: 2400,
    badge: "👨‍👩‍👧‍👦 Family",
    color: "#006400",
    items: [
      "1 Large Pizza",
      "4 Fried Wings",
      "2 Regular Fries",
      "1.5L Pepsi",
    ],
    description: "Big family feast",
    popular: true,
  },
  {
    id: "deal-16",
    name: "Party Pack",
    price: 1699,
    badge: "🎉 Party Pack",
    color: "#8B4513",
    items: [
      "2 Large Burgers",
      "2 Regular Fries",
      "2 Cold Drinks",
    ],
    description: "Party time combo",
    popular: false,
  },
];

// Export for use in app.js
if (typeof module !== "undefined") {
  module.exports = { RESTAURANT_INFO, MENU_CATEGORIES, DEALS };
}
